# -*- coding: utf-8 -*-
# INPUT DATA
INPUT_STORAGE_NAME = "challengebasf"
INPUT_STORAGE_KEY = ""
INPUT_STORAGE_URL = f"https://{INPUT_STORAGE_NAME}.blob.core.windows.net/"
INPUT_CONTAINER_NAME = "rawdata"

# SANITIZED DATA
SANITIZED_STORAGE_NAME = INPUT_STORAGE_NAME
SANITIZED_STORAGE_KEY = INPUT_STORAGE_KEY
SANITIZED_STORAGE_URL = f"https://{SANITIZED_STORAGE_NAME}.blob.core.windows.net/"
SANITIZED_CONTAINER_NAME = "sanitizeddata"

# PARQUET DATA
PARQUET_STORAGE_NAME = INPUT_STORAGE_NAME
PARQUET_STORAGE_KEY = INPUT_STORAGE_KEY
PARQUET_STORAGE_URL = f"https://{PARQUET_STORAGE_NAME}.blob.core.windows.net/"
PARQUET_CONTAINER_NAME = "parquetdata"
PARQUET_OUTPUT_FOLDER = "output_data"

# FILTERED DATA
FILTERED_STORAGE_NAME = INPUT_STORAGE_NAME
FILTERED_STORAGE_KEY = INPUT_STORAGE_KEY
FILTERED_STORAGE_URL = f"https://{FILTERED_STORAGE_NAME}.blob.core.windows.net/"
FILTERED_CONTAINER_NAME = "filtereddata"
FILTERED_OUTPUT_FOLDER = "output_data"

