# -*- coding: utf-8 -*-
# INPUT DATA
INPUT_STORAGE_NAME = "challengebasf"
INPUT_STORAGE_KEY = ""
INPUT_STORAGE_URL = f"https://{INPUT_STORAGE_NAME}.blob.core.windows.net/"
INPUT_CONTAINER_NAME = "rawdata"

# SANITIZED DATA
SANITIZED_STORAGE_NAME = INPUT_STORAGE_NAME
SANITIZED_STORAGE_KEY = INPUT_STORAGE_KEY
SANITIZED_CONTAINER_NAME = "sanitizeddata"

# PARQUET DATA
PARQUET_STORAGE_NAME = INPUT_STORAGE_NAME
PARQUET_STORAGE_KEY = INPUT_STORAGE_KEY
PARQUET_CONTAINER_NAME = "parquetdata"
PARQUET_OUTPUT_FOLDER = "output_data"

# FILTERED DATA
FILTERED_STORAGE_NAME = INPUT_STORAGE_NAME
FILTERED_STORAGE_KEY = INPUT_STORAGE_KEY
FILTERED_CONTAINER_NAME = "filtereddata"
FILTERED_OUTPUT_FOLDER = "output_data"

# PROCESSED TEXT FROM FILTERED DATA
PROCESSED_TEXT_STORAGE_NAME = INPUT_STORAGE_NAME
PROCESSED_TEXT_STORAGE_KEY = INPUT_STORAGE_KEY
PROCESSED_TEXT_CONTAINER_NAME = "processedtextdata"
PROCESSED_TEXT_OUTPUT_FOLDER = "output_data"

# FREQUENT_WORDS
FREQUENT_WORDS_STORAGE_NAME = INPUT_STORAGE_NAME
FREQUENT_WORDS_STORAGE_KEY = INPUT_STORAGE_KEY
FREQUENT_WORDS_CONTAINER_NAME = "frequentwords"
FREQUENT_WORDS_OUTPUT_FILE_NAME = "frequent_words.csv"  # Has to end with .csv

# PROCESS DATA FOR CLASSIFIER AND CLUSTEING
FEATURES_STORAGE_NAME = INPUT_STORAGE_NAME
FEATURES_STORAGE_KEY = INPUT_STORAGE_KEY
FEATURES_CONTAINER_NAME = "featurizeddata"
FEATURES_OUTPUT_FOLDER = "output_data"

# POSITIVE DATA FOR ENERGY CLASSIFIER
POSITIVE_DATA_CLASSIFIER_STORAGE_NAME = "hiringchallengespatents"
POSITIVE_DATA_CLASSIFIER_STORAGE_KEY = ""
POSITIVE_DATA_CLASSIFIER_CONTAINER_NAME = "training-data"
POSITIVE_DATA_CLASSIFIER_FILE_NAME = "energy.consumption.patent.filenames"

# CLASSIFIER MODEL (SPARK-MODEL)
ENERGY_CLASSIFIER_VERSION = "v1"
ENERGY_CLASSIFIER_STORAGE_NAME = INPUT_STORAGE_NAME
ENERGY_CLASSIFIER_STORAGE_KEY = INPUT_STORAGE_KEY
ENERGY_CLASSIFIER_CONTAINER_NAME = "classifier"
ENERGY_CLASSIFIER_OUTPUT_FOLDER = f"output_data_{ENERGY_CLASSIFIER_VERSION}"

# ENERGY PATENTS DATA
ENERGY_PATENTS_STORAGE_NAME = INPUT_STORAGE_NAME
ENERGY_PATENTS_STORAGE_KEY = INPUT_STORAGE_KEY
ENERGY_PATENTS_CONTAINER_NAME = "energypatents"
ENERGY_PATENTS_OUTPUT_FOLDER = f"output_data_{ENERGY_CLASSIFIER_VERSION}"

# LDA MODELS FOR TOPIC CLUSTERING
TOPIC_CLUSTERING_STORAGE_NAME = INPUT_STORAGE_NAME
TOPIC_CLUSTERING_STORAGE_KEY = INPUT_STORAGE_KEY
TOPIC_CLUSTERING_CONTAINER_NAME = "energypatentsclustering"
TOPIC_CLUSTERING_OUTPUT_LDA = f"lda_model"  # _<minDF> will be added
TOPIC_CLUSTERING_OUTPUT_CV = f"cv_model"
TOPIC_CLUSTERING_OUTPUT_LDA_RESULT_PREFIX = "lda_results"
TOPIC_CLUSTERING_OUTPUT_PCA = "pca_model"
TOPIC_CLUSTERING_OUTPUT_KMEANS = "kmeans_model"


DEFAULT_STORAGE_FORMAT = "parquet"
